### ISSUE TITLE
iOS application - NGInX Reverse Proxy

### ISSUE THREAD

**Issue by jaysbeekay** [OpenSprinkler/OpenSprinkler-App#129]
Using app version 2.2.4 and OS 2.1.9(2), I am unable to enable remote access to my OpenSprinkler controller with basic auth and SSL when trying to access the site from the mobile app. Accessing it using the browser prompts me for my auth creds before presenting the OpenSprinkler login page.

When configuring NGINX to just serve up SSL using a letsencrypt cert it works fine. As soon as I enable basic auth I receive a check IP / port error. I have even tried reinstalling the app.

any suggestions?

**Comment by hezechiles** [comment]
I have the same Problem.

The connection to the internet is realised via OpenVPN and provided by a NGINX proxy. It is secured with HTTP Basic Auth and SSL (Lets Encrypt). If I deactivate Basic Auth, everything works fine.

When I use the safari browser, everythink is ok. only the app have the problem. By the way: the app on android works fine :-)

**Comment by mkroesen** [comment]
I checked the **Request-Headers** on various devices today and it seems that the iOS-App is not sending the **Authorization**-Header to the server/OSPi.

Got the following Request-Headers (without SSL) with **tcpdump** on a **Debian** system:

### iOS-App Request-Headers
```http
Host: example.ospi.host
Origin: ionic://localhost
Access-Control-Request-Method: GET
Connection: keep-alive
Access-Control-Request-Headers: authorization
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
Accept-Language: de-DE,de;q=0.9
Accept-Encoding: gzip, deflate
Content-Length: 0
```
_The Authorization-Header is missing._
### Android-App Request-Headers
```http
Host: example.ospi.host
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=
User-Agent: Mozilla/5.0 (Linux; Android 11; SM-A405FN Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile Safari/537.36
X-Requested-With: com.albahra.sprinklers
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
```
_The Authorization-Header is available._
### Edge-Browser (Windows) Request-Headers
```http
Host: example.ospi.host
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Authorization: dXNlcm5hbWU6cGFzc3dvcmQ=
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
```
_The Authorization-Header is available._

The iOS-App works perfectly with and without SSL as long as Authorization is not activated. Unfortunately, I don't know how the login data is sent to the server within the app, maybe this information gets lost somewhere within the iOS-App.

Any idea where the error could be?

**Comment by mkroesen** [comment]
I have been working on this issue a little more intensively over the last few days. The iOS-App makes a [Preflight-Request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request), which can be recognised by [Access-Control-Request-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers) and [Access-Control-Request-Method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Method). The NGINX-Reverse-Proxy only needs to be configured to send the correct response.

The following configuration works perfectly for me, even with SSL:
```nginx
location / {
  # handle preflight requests
  if ($request_method = "OPTIONS") {
    add_header Access-Control-Allow-Origin $http_origin;
    add_header Access-Control-Allow-Methods $request_method;
    add_header Access-Control-Allow-Headers $http_access_control_request_headers;
    return 204;
  }
  # proxy with auth
  auth_basic "password-protected area";
  auth_basic_user_file /path/to/.htpasswd;
  proxy_pass http://example.ospi.ip:8080;
}
```
First check if it is a _Preflight-Request_ ([Request-Method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) is [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#preflighted_requests_in_cors)), if yes we send the required headers and status code to the client. It is important that the `return 204` ([status code 204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)) is present and before `auth_basic`, otherwise NGINX would continue with the authentication and respond with the [status code 401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) even if the headers in the response are sent correctly.

I can't tell why the iOS-App does the _Preflight-Request_ and all other apps and browsers don't, but I think that with the additional NGINX-Configuration it is also solved.

@jaysbeekay could you please check if that solves your problem? Then this issue and #121 could be closed.

**Comment by kmix** [comment]
FWIW, this is occurring after the last Android update (2.3.2 on July 8, 2023), as well. I run an nginx reverse proxy and am able to log in to my sites now after handling the CORS preflight.

Reference: https://opensprinkler.com/forums/topic/after-android-update-2-3-2-problems/

**Comment by salbahra** [comment]
Thank you the detailed investigation on this issue. As you discovered the preflight request has to have the proper reply for CORS to work properly. iOS was the first platform which was updated to require this and the others are being so now as well.

Going to close this issue as it's now understood to be a proxy issue.

Thank you!
