### ISSUE TITLE
Handling of Disabled Stations

### ISSUE THREAD

**Issue by silverbullettruck2001** [OpenSprinkler/OpenSprinkler-App#143]
When I disable a station it loses its name in the UI.  It reverts back to `S01` or whatever the default is.  Could this be changed to just leave all name as-is and just allow it to be disabled?

**Comment by jonathan-marsh** [comment]
I'll look at this - it's likely a bug introduced when I consolidated
station names into options.

-Jonathan

**Comment by jonathan-marsh** [comment]
Tried to reproduce this without success, changing a bunch of settings and
seeing if the station names get reset.  Can you be more specific about what
you are seeing?  Is the change happening before or after hitting the Submit
Changes button?  (Maybe the issue is in saving changes.)

The only way I saw the names revert was when I accidentally hit "Reset
Names".  I now wonder if "Reset Names" is a good name for the button to
restore the default S<n> names.  It is in the right place for a "save my
name changes" action and "reset" could be interpreted that way.  The
"Submit Changes" button is now down at the bottom of the page, less obvious
it's the next step.  Do we even need a "Reset Names" button at all?  How
often does an average user do this, and is it so hard to simply type in new
names?

**Comment by silverbullettruck2001** [comment]
I am not sure now.  I went back to reproduce again and it worked as expected.  I don't even have a button for `Reset Names`.  It does seem that resetting names would be pretty easy to do manually, unless you had a large number of stations.  I guess my issue is no longer an issue since I can't reproduce it though.  Thanks for looking into it though.

**Comment by jonathan-marsh** [comment]
Ok I actually was using the web ui not the mobile one, so my comments are
probably not relevant.  Just keeping an eye out for issues since the
station naming web ui change was my doing a few months ago ;-).

**Comment by rayshobby** [comment]
Does this issue have to do with the official OpenSprinkler mobile app, or is this referring to a different app / UI? If you are not sure, could you post a screenshot of what you are referring to?
