### ISSUE TITLE
Running program decimals

### ISSUE THREAD

**Issue by jking1224** [OpenSprinkler/OpenSprinkler-App#15]
when running a program, it shows like 12 decimal places of seconds.  I perhaps get this because I'm using OSPi with weather based water level. This modifies program to increase or decrease watering by various percent. So runtime could be calculated as 15:23.4744643 second. But don't need to display as such.

**Comment by salbahra** [comment]
Which firmware version are you using Dan's OSPi or the Unified firmware?

**Comment by jking1224** [comment]
Dan Python based. Latest version (or within a week)

On Monday, June 15, 2015, Samer Albahra <notifications@github.com> wrote:

> Which firmware version are you using Dan's OSPi or the Unified firmware?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSprinkler/OpenSprinkler-App/issues/15#issuecomment-112079767>
> .
>


-- 
Jeff King
*JSZA Enterprises*
*Web and Video Services*
jsza.com
<http://jsza.com/?utm_source=sig-block&utm_medium=email&utm_campaign=june2013>
(720) 675-9789

**Comment by salbahra** [comment]
Well, most likely the firmware is incorrectly returning floats instead of integars in the JSON. I know this doesnt occur with the Unified firmware. Furthermore, you suggested the watering adjustment is causing this however this can't be because the multiplication is done server side and the remaining runtime is all that is sent to me.

Therefore, I don't think the issue is with the app but rather the plugin modifying the runtimes (needs to sanatize the output to the same variable type as the input).
