### ISSUE TITLE
HTTP Station config getting garbled between App and Firmware

### ISSUE THREAD

**Issue by PeteBa** [OpenSprinkler/OpenSprinkler-App#49]
Linking to [github issue](https://github.com/OpenSprinkler/OpenSprinkler-Firmware/issues/70) on Firmware.

Looks like a slight incompatibility on use of encoding across station settings whether via export/input or the station settings cog in UI. 

Example config:
```
"special": {
	"8": {
		"st": 4,
		"sd": "ospi,8080,json.htm?type=command&param=switchlight&idx=99&switchcmd=On,json.htm?type=command&param=switchlight&idx=99&switchcmd=Off"
	}
}
```

Analysis:
- Station Settings Cog: UI will encode the station special data using `$.param( special )` within submitStations() but Firmware no longer uses urlDecode to convert it back to comma separated config option
- Export/Import: Export of configuration correctly writes station data to export file but importConfig() does not use `encodeURIComponent( info.sd )` before sending to Firmware. So if http station on/off commands contain "&" then Firmware will incorrectly treat that as an end-of-parameter delimiter.

**Comment by salbahra** [comment]
Thank you for documenting this. Once we understand why the firmware change is made we can assess what needs to be done from the apps perspective.

**Comment by rayshobby** [comment]
@PeteBa: encoding has not effect on comma, right? I assume so. So what's currently done is that the UI encodes the command (and comma is not encoded by default), so the firmware will merely store it and use it later. Previously the firmware will decode it, store it, and then encode it again when sending it out (in switch_httpstation function) which I thought was unnecessary. That's why this extra level of decoding and encoding have been removed.

**Comment by rayshobby** [comment]
I figured out the issue on the firmware side. See my last comment here: https://github.com/OpenSprinkler/OpenSprinkler-Firmware/issues/70

**Comment by salbahra** [comment]
#48 was reopened and merged in knowing what Ray found out. This should resolve everything app side. Will try to publish this ASAP as 1.8.0.

A subsequent firmware update will resolve the issue for OSPi/OS 2.3 users.
