### ISSUE TITLE
opensprinkler public access not available when running opensprinkler under a subdomain

### ISSUE THREAD

**Issue by atomi** [OpenSprinkler/OpenSprinkler-App#55]
my opensprinkler is running on a subdomain so a direct IP connection is not available. and it seems this is causing issues.      

to deal with this i've had open an additional port to redirect to my opensprinkler device. but it would be nice if it worked with sub domains.

**Comment by salbahra** [comment]
I am not sure I follow. Could you provide steps to reproduce or a place to test this condition. Thanks!

**Comment by rayshobby** [comment]
To access opensprinkler from outside your local network, it currently requires port forwarding. We are working to enable cloud access so that in the future port forwarding is not required. That said, cloud access has its own issues like concerns over privacy, and also reliability when Internet connection is temporarily down.

**Comment by atomi** [comment]
I'm sorry I wasn't clear earlier.    
I mean the Android app requires an IP.

![test](https://user-images.githubusercontent.com/83137/57097264-316f0b80-6ccc-11e9-9b1c-414082bf37c3.png)

**Comment by salbahra** [comment]
You can provide a domain in that field, it does not need to be an IP. Please make sure you have a valid DNS server configured for your OpenSprinkler.

**Comment by atomi** [comment]
@salbahra Thanks for the reply.  I've tried and it's not able to connect.     
Is there a special extra port the Android app needs open? I only have http port open and it is accessible via browser.
