### ISSUE TITLE
debugWU() no longer displays relevant data

### ISSUE THREAD

**Issue by PeteBa** [OpenSprinkler/OpenSprinkler-App#57]
OK, so I think we have a defect as a result of the modification to the Weather Service endpoints.

In the App,  debugWU() is now displaying the current weather conditions rather than the forecast values used to calculate the water level. This will be very confusing/unhelpful for users looking to understand the numbers better.

I think the right route to fix this properly would be for the Weather Service to include the Temp, Humidity & Precip values used in the zimmerman calculation as additional return parameters to Firmware when queried via the `weather1.py` endpoint.  Firmware should then retain these values and include them in the `/ja` status response when queried by App. Then App can display the real data used in the last water level calculation.

I know this sounds a bit convoluted but I think the logic is sound and all the code structure is already in place.

A slightly simpler alternative but possibly prone to timing issues, would be to make the suggested change to Weather Service as above but rather than passing the information via Firmware, the App could call that endpoint directly.

**Comment by salbahra** [comment]
I agree with you and I am pretty sure @rayshobby does too. I will discuss with him and see when we can include this in an update. Thanks again @PeteBa!

**Comment by rayshobby** [comment]
Yes, I agree with it -- I have always thought the firmware should retain the values used for calculating watering percentage and the app will display these values so that users can check that when they have doubts about the watering percentage calculation. In the past I've discussed with Samer about this. There were some concerns about backward compatibility. I suppose the app can choose what to do depending on what's available from /ja result -- if such data is available, use that in displaying diagnostics; otherwise query the weather server to get real-time data. We can plan for this in firmware 2.1.9.

**Comment by rmloeb** [comment]
What is the status of this issue?  My OS device has displayed the same current weather values for at least a week, and they are completely insane for this area.  Worse, the water levels make even less sense.  C'mon guys.  I know you're working hard on multiple fronts, but you broke this and we, the customers, really need your help.  The current fix for PWS is too complex for most to implement.  OS must (!!!) aggregate the hourly weather data and compute the proper data for Zimmerman so that the water level doesn't change hourly.  Please!  Right now OS is useless or even harmful.

**Comment by salbahra** [comment]
@rmloeb Right now, the major issue is the diagnostic data does not reflect the actual data used to calculate your shown watering level. The underlying issue with invalid data has been fixed though.

We plan on resolving the data not reflecting the actual values used to calculate in firmware 2.1.9.

**Comment by rmloeb** [comment]
Thanks for the update.  I am now using a local weather-server to handle the Z calculation, so I at least have some control over the water level.  I realize that the diagnostic data is not correct, but I added some logging code to weather-server so I could watch it do its magic.

**Comment by salbahra** [comment]
2.1.9 is now out and we can close this now. Thank you!
