### ISSUE TITLE
More decimal places or equation support for flow meter rate.

### ISSUE THREAD

**Issue by sachaw** [OpenSprinkler/OpenSprinkler-App#74]
Hi, I am running a flow meter that has a flow rate of (0.98/60 = 0.0163333333), however the OpenSprinkler will only let me set it to 0.01 or 0.02, neither of which is very accurate, could anybody point me to where in the codebase this is limited and I'd like to submit a PR, regards.

**Comment by rayshobby** [comment]
You can just set the flow rate to 0.16, or 1.63 or 16.3 and keep in mind to divide by the numbers you see by 10, or 100 or 1000 respectively.

**Comment by sachaw** [comment]
@rayshobby I cant seem to get that to work, if I set `Flow Pulse Rate` to `0.01`, `0.16`, `1.63` etc, it doesn't seem to scale/divide as you said, i.e. `0.01` results in ~4l/m where as `16.3` results in 4270l/m

**Comment by rayshobby** [comment]
That's what I meant: when you see the number you just manually divide (in your mind) by, 1000 in your example.

**Comment by sachaw** [comment]
thats not what I'm looking for, can someone please point me to where in the codebase it limits it to 2 decimal places?

**Comment by salbahra** [comment]
It's this regular expression here: https://github.com/OpenSprinkler/OpenSprinkler-App/blob/master/www/js/main.js#L3800

I believe the limitation is part of the firmware for number of decimal points though. I am going to close this on the app but feel free to re-open if the firmware does support more decimal points. Otherwise feel free to open a feature request on the firmware side.

Thanks!
