### ISSUE TITLE
Display rssi on interface

### ISSUE THREAD

**Issue by ruimarinho** [OpenSprinkler/OpenSprinkler-App#77]
Would it be possible to add a WiFi signal indicator according to the `settings.RSSI` value? On hover it would display the actual RSSI.

**Comment by rayshobby** [comment]
The current app already displays an adjective describing the wifi signal strength, according to the following classification:
https://github.com/OpenSprinkler/OpenSprinkler-App/blob/master/www/js/main.js#L3238
if you want to see the actual numeric value of rssi, you can use the API test script to pull the json all (/ja) and check 'rssi' variable:
http://raysfiles.com/os/TestOSAPI.html

**Comment by iofirag** [comment]
@rayshobby hi, after the first step when the device turn the AccessPoint: On, and user can select wifi.
Is there any option to see the wifi strength in the UI?

**Comment by rayshobby** [comment]
At the WiFi configuration page, the SSIDs are sorted by signal strength:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/html/ap_home.html#L72
though the signal strength is not explicitly displayed on the page. When you are connected to the AP, you can open a browser and type:
192.168.4.1/jsap
that will return the json data that includes the signal strengths.

**Comment by iofirag** [comment]
@rayshobby 
Hey, i understand that i can got this info in the AP step.

But I'm asking about the normal use, when the opensprinkler device is already connected to a wifi.
Is there any option to know how strength the connection is it?

**Comment by rayshobby** [comment]
@iofirag: that's what my first reply above, to the original question, was.

**Comment by iofirag** [comment]
you right. thanks! miss that part.
as i see in GPT, there is an option to get precent from RSSI value by this function:

```
def calculate_wifi_signal_strength(rssi):
    """
    Calculate WiFi signal strength in percentage from RSSI value.
    
    Args:
    rssi (int): The Received Signal Strength Indicator (RSSI) value.
    
    Returns:
    int: WiFi signal strength as a percentage.
    """
    # RSSI range typically varies from -100 to 0
    min_rssi = -100
    max_rssi = -50

    # Ensure the RSSI is within the valid range
    if rssi < min_rssi:
        rssi = min_rssi
    elif rssi > max_rssi:
        rssi = max_rssi

    # Calculate the signal strength percentage
    strength_percentage = (rssi - min_rssi) / (max_rssi - min_rssi) * 100
    return int(strength_percentage)

# Example usage:
rssi_value = -70
signal_strength = calculate_wifi_signal_strength(rssi_value)
print(f"WiFi Signal Strength: {signal_strength}%")
```

maybe it will nice to include that value in the response :)


by the way, 
with this app [](http://raysfiles.com/os/TestOSAPI.html)
i got CORS error. and cant get any result from the device.
so instead of get the response in the app
i do the request manually like describe there and success get results.

maybe can add flag in server for approve CORS income request to the device? 
usually it fixed by adding `Access-Control-Allow-Origin: *`

**Comment by rayshobby** [comment]
The RSSI to adjective translation is done on the UI side:
https://github.com/OpenSprinkler/OpenSprinkler-App/blob/master/www/js/main.js#L3384
if you use the OpenSprinkler mobile app or the web UI, it shows the adjective in the System Diagnostics.

The script at raysfiles.com is not an app, it's a API testing script. I don't believe the issue you encountered is due to CORS, because the firmware already inserts CORS:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/opensprinkler_server.cpp#L118
the issue is likely that you are using the script in Chrome browser -- Chrome enforces no mixed content, which causes issues if you use the script with direct IP access. So either you need to use a different browser, like Firefox, or if you use OTC token, then it's not an issue any more.

**Comment by iofirag** [comment]
Beautiful. Thanks.!
